name: MCTrapsRanking
version: ${project.version}
main: eu.mctraps.ranking.Ranking
authors: [KajmaczeK]
description: Ranking
depends: [MCTrapsDisplayer]
website: https://mctraps.eu
commands:
  ranking:
    description: ranking
    usage: /ranking